FROM node:21

WORKDIR /app/frontend

# Install dependencies
COPY package.json tsconfig.json ./
RUN npm install 

# Copy the project files and build the app
COPY . .
RUN npm run build

# Serve the app with Bun's built-in server
# EXPOSE 3000

CMD ["npm", "run", "prod", "--", "--host"]
