import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :time_manager, TimeManagerWeb.Endpoint,
  # cache_static_manifest: "priv/static/cache_manifest.json",
  secret_key_base: System.get_env("SECRET_KEY_BASE"),
  http: [port: String.to_integer(System.get_env("PORT") || "4000")]

# Configure your database using the DATABASE_URL environment variable
config :time_manager, TimeManager.Repo,
  url: System.get_env("DATABASE_URL"),
  pool_size: String.to_integer(System.get_env("POOL_SIZE") || "10")

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: TimeManager.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

config :time_manager, TimeManager.Guardian,
  # Name of your application or domain
  issuer: "time_manager",
  # You should use a secure and random key
  secret_key: "wZZmhgb5huThibmm7YOJ131OdAQbm5VbnfXcZWtUZ7RUWe9KsBve9zTSYltVzdXF"

config :time_manager, TimeManager.Mailer,
  adapter: Swoosh.Adapters.SMTP,
  relay: "ssl0.ovh.net",
  username: System.get_env("OVH_SMTP_USERNAME"),
  password: System.get_env("OVH_SMTP_PASSWORD"),
  port: 587,
  tls: :always,
  auth: :always,
  # Disable SSL
  ssl: false,
  retries: 1,
  no_mx_lookups: false,
  # Disable peer verification
  tls_options: [verify: :verify_none]

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
